### ISSUE TITLE
Mini Lightbox: mobile spacing issue

### ISSUE THREAD

**Issue by edvardsniedre** [eBay/skin#1301]
Skin v11.0.0 Mini Lightbox does not fit in on mobile due to `max-width`.
![mini-dialog-mobile-spacing](https://user-images.githubusercontent.com/7050068/99967721-27ba6680-2d90-11eb-9134-569010f0b4e0.gif)

**Comment by austingardner** [comment]
I will look into this this week - thanks for letting us know Edvards

**Comment by austingardner** [comment]
Hi Edvards - we have fixed this issue in skin v12. We will be doing a pre-release of skin v12 probably next week which will have this fix. 

Thanks for filing an issue and helping us out! 😄

**Comment by ianmcburnie** [comment]
We can also look into back-porting this fix to 11.0.x if it's simple.

**Comment by ianmcburnie** [comment]
This was fixed in 12.0.0. Closing.

**Comment by edvardsniedre** [comment]
Issue is still present in v12.0.1

**Comment by ianmcburnie** [comment]
Still appears to be an issue, so re-opening.

https://github.com/eBay/skin/issues/1380#issuecomment-804452924

**Comment by ianmcburnie** [comment]
Fixed in 12.3.0
